# Stage 1: Build
FROM node:18-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


FROM nginx:alpine
# ก๊อปปี้ไฟล์หน้าเว็บทั้งหมดไปไว้ในโฟลเดอร์เสิร์ฟงานของ Nginx
COPY . /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]