services:
  db:
    image: postgres:15-alpine
    container_name: libbook_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=libbook_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: libbook_api
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=libbook_db
      - PORT=3001
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: libbook_web
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata: